export const FETCH_BUSINESS_DETAIL = 'fetch_business_detail';
export const FETCH_BUSINESS_DETAILS = 'fetch_business_details';

export const FETCH_BUSINESS_NEIGHBORHOOD_SUCCESS = 'fetch_business_neighborhood_success';

export const FETCH_BUSINESS_USER_RECOMMENDATION_REQUEST = 'FETCH_BUSINESS_RECOMMENDATION_REQUEST';
export const FETCH_BUSINESS_USER_RECOMMENDATION_SUCCESS = 'FETCH_BUSINESS_RECOMMENDATION_SUCCESS';
export const FETCH_BUSINESS_USER_RECOMMENDATION_FAILURE = 'FETCH_BUSINESS_RECOMMENDATION_FAILURE';
export const SET_BUSINESS_USER_RECOMMENDATION_SUCCESS = 'SET_BUSINESS_USER_RECOMMENDATION_SUCCESS';

export const FETCH_BUSINESS_RECOMMENDATIONS_REQUEST = 'FETCH_BUSINESS_RECOMMENDATIONS_REQUEST';
export const FETCH_BUSINESS_RECOMMENDATIONS_SUCCESS = 'FETCH_BUSINESS_RECOMMENDATIONS_SUCCESS';
export const FETCH_BUSINESS_RECOMMENDATIONS_FAILURE = 'FETCH_BUSINESS_RECOMMENDATIONS_FAILURE';

export const BOOKMARK_BUSINESS_REQUEST = 'BOOKMARK_BUSINESS_REQUEST';
export const BOOKMARK_BUSINESS_SUCCESS = 'BOOKMARK_BUSINESS_SUCCESS';
export const BOOKMARK_BUSINESS_FAILURE = 'BOOKMARK_BUSINESS_FAILURE';

export const FETCH_BUSINESS_BOOKMARKS_SUCCESS = 'FETCH_BUSINESS_BOOKMARKS_SUCCESS';

export const SELECT_BUSINESS = 'SELECT_BUSINESS';
export const BUSINESS_SELECTED = 'BUSINESS_SELECTED';
