export const DISCOVER_TOP_REVIEWERS_UPDATE = 'DISCOVER_TOP_REVIEWERS_UPDATE';
export const FETCH_DISCOVER_DATA_REQUEST = 'FETCH_DISCOVER_DATA_REQUEST';
export const FETCH_DISCOVER_DATA_SUCCESS = 'FETCH_DISCOVER_DATA_SUCCESS';
export const FETCH_DISCOVER_DATA_FAILURE = 'FETCH_DISCOVER_DATA_FAILURE';
