export const REVIEW_BUSINESS_SELECTED = 'REVIEW_BUSINESS_SELECTED';
export const REVIEW_BUSINESS_RATED = 'REVIEW_BUSINESS_RATED';
export const REVIEW_BUSINESS_TEXT_ADDED = 'REVIEW_BUSINESS_TEXT_ADDED';
