
export const RESET_UI_ERROR_VALUES = 'RESET_UI_ERROR_VALUES';
export const FORM_DATA_LOADING = 'form_data_loading';
export const REACT_NATIVE_ROUTER_FLUX_FOCUS = 'REACT_NATIVE_ROUTER_FLUX_FOCUS';
export const REACT_NATIVE_ROUTER_FLUX_RESET = 'REACT_NATIVE_ROUTER_FLUX_RESET';
